# Generated by Django 3.2.9 on 2021-11-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EB_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_phase', models.IntegerField()),
                ('door_number', models.CharField(max_length=120, null=True)),
                ('street', models.CharField(max_length=120, null=True)),
                ('city', models.CharField(max_length=120)),
                ('post_office', models.CharField(max_length=120)),
                ('taluk', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('pin_number', models.IntegerField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EB_App.account')),
            ],
        ),
    ]
