# Generated by Django 3.2.9 on 2021-11-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_App', '0002_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='door_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
