# Generated by Django 3.2.9 on 2021-11-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_App', '0004_consumer_eb_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='eb_number',
            field=models.CharField(max_length=14),
        ),
    ]
