# Generated by Django 3.2.9 on 2021-11-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EB_App', '0005_alter_consumer_eb_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithinADayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('power_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_power_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EB_App.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='WeekWiseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
                ('power_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_power_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EB_App.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='MonthWiseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('power_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_power_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EB_App.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='DayWiseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
                ('day', models.IntegerField()),
                ('power_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_power_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EB_App.consumer')),
            ],
        ),
    ]
