# Generated by Django 3.2.9 on 2021-11-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EB_App', '0006_daywisedata_monthwisedata_weekwisedata_withinadaydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('last_bill_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('present_bill_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('power_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EB_App.consumer')),
            ],
        ),
    ]
