# Generated by Django 3.2.9 on 2021-12-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_App', '0009_auto_20211227_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='last_bill_reading',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='power_consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='present_bill_reading',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='daywisedata',
            name='average_current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='daywisedata',
            name='average_power_factor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='daywisedata',
            name='average_voltage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='daywisedata',
            name='power_consumed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthwisedata',
            name='average_current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthwisedata',
            name='average_power_factor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthwisedata',
            name='average_voltage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthwisedata',
            name='power_consumed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weekwisedata',
            name='average_current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weekwisedata',
            name='average_power_factor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weekwisedata',
            name='average_voltage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weekwisedata',
            name='power_consumed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='withinadaydata',
            name='average_current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='withinadaydata',
            name='average_power_factor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='withinadaydata',
            name='average_voltage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='withinadaydata',
            name='power_consumed',
            field=models.FloatField(),
        ),
    ]
